In [119]:
import requests 
import pandas as pd


In [120]:
docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [121]:
documents[2]

{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
 'section': 'General course-related questions',
 'question': 'Course - Can I still join the course after the start date?',
 'course': 'data-engineering-zoomcamp'}

In [122]:
df =  pd.DataFrame(documents, columns = ['course', 'section', 'question', 'text'])

In [123]:
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [124]:
df.tail()

course                   section  \
943  mlops-zoomcamp  Module 6: Best practices   
944  mlops-zoomcamp  Module 6: Best practices   
945  mlops-zoomcamp  Module 6: Best practices   
946  mlops-zoomcamp  Module 6: Best practices   
947  mlops-zoomcamp  Module 6: Best practices   

                                              question  \
943  Github actions: Permission denied error when e...   
944  Managing Multiple Docker Containers with docke...   
945           AWS regions need to match docker-compose   
946                                   Isort Pre-commit   
947  How to destroy infrastructure created via GitH...   

                                                  text  
943  Problem description\nThis is the step in the c...  
944  Problem description\nWhen a docker-compose fil...  
945  Problem description\nIf you are having problem...  
946  Problem description\nPre-commit command was fa...  
947  Problem description\nInfrastructure created in...

In [125]:
df[df.course == 'data-engineering-zoomcamp']

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
3    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
..                         ...                               ...   
430  data-engineering-zoomcamp           Workshop 2 - RisingWave   
431  data-engineering-zoomcamp           Workshop 2 - RisingWave   
432  data-engineering-zoomcamp           Workshop 2 - RisingWave   
433  data-engineering-zoomcamp          Triggers in Mage via CLI   
434  data-engineering-zoomcamp          Triggers in Mage via CLI   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
2    Course - Can I still join the course after the...   
3    Course - I have registered for the Data Engine...   
4     Course - What can I do before the course starts?   
..                                                 ...   
430  Unable to Open Dashboard as xdg-open doesn’t o...   
431  Resolving Python Interpreter Path Inconsistenc...   
432                    How does windowing work in Sql?   
433  Encountering the error "ModuleNotFoundError: N...   
434                                     Basic Commands   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
2    Yes, even if you don't register, you're still ...  
3    You don't need it. You're accepted. You can al...  
4    You can start by installing and setting up all...  
..                                                 ...  
430  Refer to the solution given in the first solut...  
431  Example Error:\nWhen attempting to execute a P...  
432  Ans : Windowing in streaming SQL involves defi...  
433  Python 3.12.1, is not compatible with kafka-py...  
434  Docker Commands\n# Create a Docker Image from ...  

[435 rows x 4 columns]

Vector Spaces

- turn the docs into vectors
- term document metrix
      - rows: documents
      - columns: workds/tokens
- bag of words
      - 

In [126]:
from sklearn.feature_extraction.text import CountVectorizer

In [127]:
cv.fit(df.text)

TfidfVectorizer(min_df=5, stop_words='english')

In [128]:
cv.get_feature_names_out() #.shape

array(['01', '02', '03', ..., 'youtube', 'zip', 'zoomcamp'], dtype=object)

In [129]:
doc_examples = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [130]:
cv = CountVectorizer(stop_words = 'english')

In [131]:
cv.fit(doc_examples)

CountVectorizer(stop_words='english')

In [132]:
cv.get_feature_names_out()

array(['15th', '2024', 'cloud', 'course', 'date', 'github', 'google',
       'homeworks', 'jan', 'listed', 'participation', 'prerequisites',
       'python', 'registration', 'required', 'setup', 'start', 'starts',
       'submit'], dtype=object)

In [133]:
X = cv.transform(doc_examples)

In [134]:
pd.DataFrame(X.todense(), columns=cv.get_feature_names_out()).T

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [135]:
from sklearn.feature_extraction.text import CountVectorizer

In [136]:
cv = CountVectorizer(stop_words='english', min_df = 5)
X = cv.fit_transform(df.text)
names = cv.get_feature_names_out()
df_docs = pd.DataFrame(X.toarray(), columns =names)
df_docs

01  02  03  04  05  06  09  10  100  11  ...  y_val  yaml  year  yellow  \
0     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
1     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
2     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
3     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
4     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ...    ...   ...   ...     ...   
943   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
944   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
945   0   0   0   0   0   0   0   0    0   0  ...      0     1     0       0   
946   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
947   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   

     yellow_tripdata_2021  yes  yml  youtube  zip  zoomcamp  
0                       0    0    0        0    0         0  
1                       0    0    0        0    0         1  
2                       0    1    0        0    0         0  
3                       0    0    0        0    0         0  
4                       0    0    0        0    0         0  
..                    ...  ...  ...      ...  ...       ...  
943                     0    0    1        0    0         0  
944                     0    0    0        0    0         0  
945                     0    0    0        0    0         0  
946                     0    0    0        0    0         0  
947                     0    0    0        0    0         1  

[948 rows x 1333 columns]

In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [138]:
cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs.round(2)

0     1     2    3    4     5     6    7     8     9    ...  938  \
01        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
02        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
03        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
04        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
05        0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
...       ...   ...   ...  ...  ...   ...   ...  ...   ...   ...  ...  ...   
yes       0.0  0.00  0.28  0.0  0.0  0.00  0.21  0.2  0.15  0.00  ...  0.0   
yml       0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
youtube   0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.15  ...  0.0   
zip       0.0  0.00  0.00  0.0  0.0  0.00  0.00  0.0  0.00  0.00  ...  0.0   
zoomcamp  0.0  0.43  0.00  0.0  0.0  0.19  0.00  0.0  0.00  0.00  ...  0.0   

          939  940  941  942   943  944  945  946   947  
01        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
02        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
03        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
04        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
05        0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
...       ...  ...  ...  ...   ...  ...  ...  ...   ...  
yes       0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
yml       0.0  0.0  0.0  0.0  0.11  0.0  0.0  0.0  0.00  
youtube   0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
zip       0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.00  
zoomcamp  0.0  0.0  0.0  0.0  0.00  0.0  0.0  0.0  0.15  

[1333 rows x 948 columns]

In [139]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

In [140]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [141]:
cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)


In [142]:
X


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

In [158]:
query = "Is It too late to join the course?"
q = cv.transform([query])
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [159]:
query_dict = dict(zip(names, q.toarray()[0]))
#query_dict


In [160]:
doc_dict = dict(zip(names, X.toarray()[2]))
doc_dict

{'01': np.float64(0.0),
 '02': np.float64(0.0),
 '03': np.float64(0.0),
 '04': np.float64(0.0),
 '05': np.float64(0.0),
 '06': np.float64(0.0),
 '09': np.float64(0.0),
 '10': np.float64(0.0),
 '100': np.float64(0.0),
 '11': np.float64(0.0),
 '12': np.float64(0.0),
 '127': np.float64(0.0),
 '13': np.float64(0.0),
 '14': np.float64(0.0),
 '15': np.float64(0.0),
 '16': np.float64(0.0),
 '17': np.float64(0.0),
 '19': np.float64(0.0),
 '1st': np.float64(0.0),
 '20': np.float64(0.0),
 '2019': np.float64(0.0),
 '2020': np.float64(0.0),
 '2021': np.float64(0.0),
 '2022': np.float64(0.0),
 '2023': np.float64(0.0),
 '2024': np.float64(0.0),
 '21': np.float64(0.0),
 '22': np.float64(0.0),
 '24': np.float64(0.0),
 '25': np.float64(0.0),
 '2pacx': np.float64(0.0),
 '30': np.float64(0.0),
 '35': np.float64(0.0),
 '403': np.float64(0.0),
 '42': np.float64(0.0),
 '50': np.float64(0.0),
 '5000': np.float64(0.0),
 '5431': np.float64(0.0),
 '5432': np.float64(0.0),
 '60': np.float64(0.0),
 '600': np.floa

In [161]:
X.dot(q.T).todense()

matrix([[0.53736733],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.19635311],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.17749108],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.10826734],
        [0.        ],
        [0.        ],
        [0.0842034 ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.23854563],
        [0.11765878],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.30696097],
        [0.07918946],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.05774537],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.07983913],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [162]:
from sklearn.metrics.pairwise import cosine_similarity

In [163]:
score = cosine_similarity(X, q).flatten()

In [164]:
import numpy as np

In [166]:
np.argsort(score) [-5:]

array([ 27, 448, 449, 440,   0])

In [167]:
df.iloc[449].text

'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'

In [182]:
fields = ['section', 'question', 'text']

In [183]:
matrices = {}
vectorizers = {}

for f in fields:
    cv = TfidfVectorizer(stop_words='english', min_df=5)
    X = cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers[f] = cv

In [184]:
matrices

{'section': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 3090 stored elements and shape (948, 66)>,
 'question': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 3431 stored elements and shape (948, 291)>,
 'text': <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 23808 stored elements and shape (948, 1333)>}

In [185]:
vectorizers

{'section': TfidfVectorizer(min_df=5, stop_words='english'),
 'question': TfidfVectorizer(min_df=5, stop_words='english'),
 'text': TfidfVectorizer(min_df=5, stop_words='english')}

In [186]:
n = len(df)

In [211]:
score = np.zeros(n)

query = "I just discovered the course, is ittoo late to join ?"

boosts = {
    'question' :3
    #'text': 0.5
}

for f in fields:
    q=vectorizers[f].transform([query])
    X = matrices[f]
    f_score = cosine_similarity(X, q).flatten()
    boost = boosts.get(f, 1.0)
    score = score + boost * f_score
    
    

In [212]:
score

array([3.52985023, 3.49512426, 2.70735166, 2.96614194, 3.49512426,
       3.49512426, 1.93689291, 3.67069698, 2.67242848, 3.49512426,
       3.10198469, 2.46096752, 0.49512426, 0.49512426, 0.49512426,
       0.59193348, 0.49512426, 2.63772182, 0.57041627, 0.49512426,
       0.49512426, 0.49512426, 0.79499188, 0.60033101, 0.49512426,
       0.49512426, 0.49512426, 0.76959902, 0.62340833, 0.49512426,
       0.49512426, 0.49512426, 0.49512426, 1.78972334, 3.49512426,
       1.72080809, 0.49512426, 0.49512426, 0.49512426, 0.52668735,
       0.54427244, 2.00115141, 0.49512426, 0.53842198, 0.        ,
       0.        , 0.        , 0.        , 0.02804374, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06739038, 0.        , 0.00980845,
       0.        , 0.        , 0.        , 0.        , 0.05820102,
       0.        , 0.        , 0.        , 0.        , 0.     

In [213]:
filter = {
    'course': 'data-engineering-zoomcamp'
}

In [214]:
for field, value in filter.items():
    mask = (df[field] == value).astype(int).values
    score = score * mask

score

array([3.52985023, 3.49512426, 2.70735166, 2.96614194, 3.49512426,
       3.49512426, 1.93689291, 3.67069698, 2.67242848, 3.49512426,
       3.10198469, 2.46096752, 0.49512426, 0.49512426, 0.49512426,
       0.59193348, 0.49512426, 2.63772182, 0.57041627, 0.49512426,
       0.49512426, 0.49512426, 0.79499188, 0.60033101, 0.49512426,
       0.49512426, 0.49512426, 0.76959902, 0.62340833, 0.49512426,
       0.49512426, 0.49512426, 0.49512426, 1.78972334, 3.49512426,
       1.72080809, 0.49512426, 0.49512426, 0.49512426, 0.52668735,
       0.54427244, 2.00115141, 0.49512426, 0.53842198, 0.        ,
       0.        , 0.        , 0.        , 0.02804374, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06739038, 0.        , 0.00980845,
       0.        , 0.        , 0.        , 0.        , 0.05820102,
       0.        , 0.        , 0.        , 0.        , 0.     

In [216]:
idx = np.argsort(score) [-10:]

In [217]:
df.iloc[idx]

course                           section  \
3    data-engineering-zoomcamp  General course-related questions   
411  data-engineering-zoomcamp               Workshop 1 - dlthub   
10   data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
34   data-engineering-zoomcamp  General course-related questions   
9    data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
5    data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   

                                              question  \
3    Course - I have registered for the Data Engine...   
411                               Edit Course Profile.   
10   Course - ​​How many hours per week am I expect...   
1    Course - What are the prerequisites for this c...   
34                How can we contribute to the course?   
9    Course - Which playlist on YouTube should I re...   
4     Course - What can I do before the course starts?   
5               Course - how many Zoomcamps in a year?   
0                 Course - When will the course start?   
7    Course - Can I follow the course after it fini...   

                                                  text  
3    You don't need it. You're accepted. You can al...  
411  The display name listed on the leaderboard is ...  
10   It depends on your background and previous exp...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
34   Star the repo! Share it with friends if you fi...  
9    All the main videos are stored in the Main “DA...  
4    You can start by installing and setting up all...  
5    There are 3 Zoom Camps in a year, as of 2024. ...  
0    The purpose of this document is to capture fre...  
7    Yes, we will keep all the materials after the ...

In [218]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [219]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just singned up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

In [220]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

In [221]:
from sklearn.decomposition import TruncatedSVD

In [223]:
X = matrices['text']
cv = vectorizers['text']

In [224]:
cv

TfidfVectorizer(min_df=5, stop_words='english')

In [225]:
svd = TruncatedSVD(n_components = 16)
X_emb = svd.fit_transform(X)

In [226]:
X_emb.shape

(948, 16)

In [227]:
X_emb[0]

array([ 0.09652414, -0.08217368, -0.10263733, -0.07892142,  0.06800636,
       -0.05851029, -0.00267005, -0.1675466 ,  0.22165846, -0.26145954,
        0.11808216,  0.04304113, -0.12815019, -0.07568412,  0.00452894,
       -0.03500585])

In [229]:
query = "I just singned up. Is it too late to join the course?"


Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.05790034, -0.03847312, -0.05645483, -0.02766688,  0.03935277,
       -0.0616627 , -0.00287979, -0.10680249,  0.15531765, -0.1704651 ,
        0.09453471,  0.04771492, -0.0972637 , -0.04247864,  0.01228869,
       -0.02285327])

In [230]:
np.dot(X_emb[0], Q_emb[0])

np.float64(0.14966310305701813)

In [232]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(score)[:10]
list(df.loc[idx].text)

['PULocationID will not be recognized but “PULocationID” will be. This is because unquoted "Localidentifiers are case insensitive. See docs.',
 'When I run   import tflite_runtime.interpreter as tflite , I get an error message says “ImportError: generic_type: type "InterpreterWrapper" is already registered!”\nSolution description\nThis error occurs when you import both tensorflow  and tflite_runtime.interpreter  “import tensorflow as tf” and “import tflite_runtime.interpreter as tflite” in the same notebook.  To fix the issue, restart the kernel and import only tflite_runtime.interpreter " import tflite_runtime.interpreter as tflite".\nAsia Saeed',
 'Yellow Trips: https://www1.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf\nGreen Trips: https://www1.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_green.pdf',
 "You may get an error while creating a bucket with localstack and the boto3 client:\nbotocore.exceptions.ClientError: An error occurred (Il

In [234]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\decomposition\_nmf.py:1759: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00052888, 0.        , 0.26082207, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])